[package]
name = "prisma_os"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader = "0.11.9"
bootloader_api = "0.11.9"
volatile = "0.2.6"
spin = "0.5.2"
x86_64 = "0.14.2"
uart_16550 = "0.2.0"
pic8259 = "0.10.1"
pc-keyboard = "0.5.0"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }

[[bin]]
name = "prisma_os"
path = "src/main.rs"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[build]
target = "x86_64-prisma"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.'cfg(target_os = "none")']
runner = "bootimage runner"