[package]
name = "prisma_os"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader-boot-config = { version = "0.11.9", default-features = false }
bootloader_api = { version = "0.11.9", default-features = false }
volatile = { version = "0.2.6", default-features = false }
spin = { version = "0.5.2", default-features = false }
x86_64 = { version = "0.14.2", default-features = false, features = ["const_fn", "nightly"] }
uart_16550 = { version = "0.2.0", default-features = false }
pic8259 = { version = "0.10.1", default-features = false }
pc-keyboard = { version = "0.5.0", default-features = false }
lazy_static = { version = "1.4.0", features = ["spin_no_std"], default-features = false }

[build-dependencies]
bootloader = "0.11.9"

[[bin]]
name = "prisma_os"
path = "src/main.rs"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[build]
target = "x86_64-prisma"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
