[package]
name = "prisma_os"
version = "0.1.0"
edition = "2021"

[lib]
name = "prisma_os"
path = "src/lib.rs"

[[bin]]
name = "prisma_os"
path = "src/main.rs"

[dependencies]
bootloader = "0.11.9"
volatile = "0.2.6"
spin = "0.5.2"
x86_64 = "0.14.2"
uart_16550 = "0.2.0"
pic8259 = "0.10.1"
pc-keyboard = "0.5.0"
static_assertions = "1.1.0"

# Important: Use the spin_no_std feature for lazy_static
[dependencies.lazy_static]
version = "1.4.0"
features = ["spin_no_std"]

# Disable default features for all dependencies that might pull in std
[dependencies.crossbeam-queue]
version = "0.2.1"
default-features = false
features = ["alloc"]

[dependencies.conquer-once]
version = "0.2.0"
default-features = false

[dependencies.futures-util]
version = "0.3.4"
default-features = false
features = ["alloc"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"