[build]
target = "x86_64-prisma"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.x86_64-prisma]
linker = "clang"
rustflags = [
    "-C", "link-arg=-fuse-ld=lld",
    "-C", "link-args=-nostartfiles",
    "-C", "link-args=-static"
]